import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [color,setColor]=useState('');
  const [opening,setOpening]=useState('');
  useEffect(() => {
    setInterval(() => {
      const now = new Date();
      const day = now.getDay(); // returns a number representing the day of the week, starting with 0 for Sunday
      const hours = now.getHours();
      const minutes = now.getMinutes();
      const seconds = now.getSeconds();
      if (day == 1 || day == 2 || day == 3 || day == 4 || day == 5) {
       if(hours>=10 && hours <19 || hours == 19  && minutes == 0)
       {
        setColor('green');
        setOpening('Open');
       }
       else{
        setColor('red');
        setOpening('closed');
       } 
      }
      else if(day==6)
      {
        if((hours>=12 && hours<15)||(hours==15 && minutes==0))
        {
          setColor('green');
          setOpening('open');
        }
        else{
          setColor('red');
          setOpening('closed');
        
        }

      }
      else{
        setColor('red');
        setOpening('closed');
      }
      console.log(`Today is day ${day} and the time is ${hours}:${minutes}:${seconds}.`);
    }, 1000);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{color}||||{opening}</h1>
    </>
  );
}
